#!/bin/bash

# Copyright 2019 Toyota Research Institute.  All rights reserved.

# Git pre-push hook to check commited Python files for pylint issues with
# driving pylintrc. If there are any pylint errors, it will exit with an error.

BRANCH=$(git rev-parse --abbrev-ref HEAD)

# check if remote branch exists
REMOTE=origin
REMOTE_BRANCH=$REMOTE/$BRANCH
git branch -a | grep $REMOTE_BRANCH
if [ $? = 1 ]; then
  REMOTE_BRANCH=$REMOTE/master
fi

COMMITED_PYTHON_FILES=$(git diff --name-only --diff-filter=ACM --name-only \
                        $REMOTE_BRANCH..$BRANCH | grep --color=never '.py$')

if [[ "$COMMITED_PYTHON_FILES" = "" ]]; then
  echo 'No python files to lint.'
else
  pylint $COMMITED_PYTHON_FILES
  if [ $? -ne 0 ]
  then
    echo "Aborting push due to files with lint."
    exit 1
  fi
fi
exit 0
