language: python
jobs:
  include:
    - name: "Python 3.7 on Bionic Linux"
      dist: bionic
      python: 3.7
    - name: "Python 3.6 on Bionic Linux"
      dist: bionic
      python: 3.6
# command to install dependencies
install:
  - pip install cython==0.29.10 numpy==1.19.4
  - pip install -r requirements.txt
# command to run tests
script:
  - cd $TRAVIS_BUILD_DIR
  - make test