# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/contribs/pd/metadata.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64gp/contribs/pd/metadata.proto\x12\tdgp.proto\"\x9e\x01\n\x1cParallelDomainSampleMetadata\x12K\n\nattributes\x18\x01 \x03(\x0b\x32\x37.dgp.proto.ParallelDomainSampleMetadata.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd4\x03\n\x1bParallelDomainSceneMetadata\x12\x10\n\x08location\x18\x01 \x01(\t\x12*\n\x0bregion_type\x18\t \x01(\x0e\x32\x15.dgp.proto.RegionType\x12(\n\nscene_type\x18\n \x01(\x0e\x32\x14.dgp.proto.SceneType\x12\x13\n\x0btime_of_day\x18\x02 \x01(\t\x12\x15\n\rsun_elevation\x18\x0b \x01(\x02\x12\x13\n\x0bsun_azimuth\x18\x0c \x01(\x02\x12\x13\n\x0b\x63loud_cover\x18\r \x01(\x02\x12\x15\n\rfog_intensity\x18\x03 \x01(\x02\x12\x16\n\x0erain_intensity\x18\x04 \x01(\x02\x12\x0f\n\x07wetness\x18\x05 \x01(\x02\x12\x15\n\rstreet_lights\x18\x06 \x01(\x02\x12\x10\n\x08\x62\x61tch_id\x18\x07 \x01(\r\x12\x0f\n\x07version\x18\x08 \x01(\r\x12J\n\nattributes\x18\x0e \x03(\x0b\x32\x36.dgp.proto.ParallelDomainSceneMetadata.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*F\n\tSceneType\x12\x13\n\x0fSYNTHETIC_SCENE\x10\x00\x12\t\n\x05URBAN\x10\x01\x12\x0c\n\x08SUBURBAN\x10\x02\x12\x0b\n\x07HIGHWAY\x10\x03*I\n\nRegionType\x12\x14\n\x10SYNTHETIC_REGION\x10\x00\x12\x17\n\x13NORTHERN_CALIFORNIA\x10\x01\x12\x0c\n\x08MICHIGAN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.contribs.pd.metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PARALLELDOMAINSAMPLEMETADATA_ATTRIBUTESENTRY']._options = None
  _globals['_PARALLELDOMAINSAMPLEMETADATA_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_PARALLELDOMAINSCENEMETADATA_ATTRIBUTESENTRY']._options = None
  _globals['_PARALLELDOMAINSCENEMETADATA_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_SCENETYPE']._serialized_start=677
  _globals['_SCENETYPE']._serialized_end=747
  _globals['_REGIONTYPE']._serialized_start=749
  _globals['_REGIONTYPE']._serialized_end=822
  _globals['_PARALLELDOMAINSAMPLEMETADATA']._serialized_start=46
  _globals['_PARALLELDOMAINSAMPLEMETADATA']._serialized_end=204
  _globals['_PARALLELDOMAINSAMPLEMETADATA_ATTRIBUTESENTRY']._serialized_start=155
  _globals['_PARALLELDOMAINSAMPLEMETADATA_ATTRIBUTESENTRY']._serialized_end=204
  _globals['_PARALLELDOMAINSCENEMETADATA']._serialized_start=207
  _globals['_PARALLELDOMAINSCENEMETADATA']._serialized_end=675
  _globals['_PARALLELDOMAINSCENEMETADATA_ATTRIBUTESENTRY']._serialized_start=155
  _globals['_PARALLELDOMAINSCENEMETADATA_ATTRIBUTESENTRY']._serialized_end=204
# @@protoc_insertion_point(module_scope)
