# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/radar_point_cloud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgp.proto import geometry_pb2 as dgp_dot_proto_dot_geometry__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dgp/proto/radar_point_cloud.proto',
  package='dgp.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!dgp/proto/radar_point_cloud.proto\x12\tdgp.proto\x1a\x18\x64gp/proto/geometry.proto\x1a\x19google/protobuf/any.proto\"\xaa\x07\n\x0fRadarPointCloud\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12@\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32+.dgp.proto.RadarPointCloud.AnnotationsEntry\x12:\n\x08metadata\x18\x03 \x03(\x0b\x32(.dgp.proto.RadarPointCloud.MetadataEntry\x12<\n\x0cpoint_format\x18\x04 \x03(\x0e\x32&.dgp.proto.RadarPointCloud.ChannelType\x12\x14\n\x0cpoint_fields\x18\x05 \x03(\t\x12\x1d\n\x04pose\x18\x06 \x01(\x0b\x32\x0f.dgp.proto.Pose\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"\x98\x04\n\x0b\x43hannelType\x12\x05\n\x01X\x10\x00\x12\x05\n\x01Y\x10\x01\x12\x05\n\x01Z\x10\x02\x12\x07\n\x03V_X\x10\x03\x12\x07\n\x03V_Y\x10\x04\x12\x07\n\x03V_Z\x10\x05\x12\x0c\n\x08RCS_DBSM\x10\x06\x12\x19\n\x15\x45XISTENCE_PROBABILITY\x10\x07\x12\r\n\tSENSOR_ID\x10\x08\x12\n\n\x06\x43OV_XX\x10\t\x12\n\n\x06\x43OV_XY\x10\n\x12\n\n\x06\x43OV_XZ\x10\x0b\x12\n\n\x06\x43OV_YX\x10\x0c\x12\n\n\x06\x43OV_YY\x10\r\x12\n\n\x06\x43OV_YZ\x10\x0e\x12\n\n\x06\x43OV_ZX\x10\x0f\x12\n\n\x06\x43OV_ZY\x10\x10\x12\n\n\x06\x43OV_ZZ\x10\x11\x12\x13\n\x0fRADIAL_DISTANCE\x10\x12\x12\x11\n\rAZIMUTH_ANGLE\x10\x13\x12\x13\n\x0f\x45LEVATION_ANGLE\x10\x14\x12\x0f\n\x0bVELOCITY_XS\x10\x15\x12\x1c\n\x18RADIAL_DISTANCE_VARIANCE\x10\x16\x12\x1a\n\x16\x41ZIMUTH_ANGLE_VARIANCE\x10\x17\x12\x1c\n\x18\x45LEVATION_ANGLE_VARIANCE\x10\x18\x12\x15\n\x11VELOCITY_VARIANCE\x10\x19\x12\x0c\n\x08\x41\x43\x43\x45L_XS\x10\x1a\x12\x0f\n\x0b\x43OUNT_ALIVE\x10\x1b\x12\x16\n\x12REFLECTED_POWER_DB\x10\x1c\x12\x05\n\x01R\x10\x1d\x12\x05\n\x01G\x10\x1e\x12\x05\n\x01\x42\x10\x1f\x12\x0c\n\x08\x43LASS_ID\x10 \x12\x0f\n\x0bINSTANCE_ID\x10!\x12\r\n\tTIMESTAMP\x10\"b\x06proto3'
  ,
  dependencies=[dgp_dot_proto_dot_geometry__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_RADARPOINTCLOUD_CHANNELTYPE = _descriptor.EnumDescriptor(
  name='ChannelType',
  full_name='dgp.proto.RadarPointCloud.ChannelType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='X', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Y', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Z', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='V_X', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='V_Y', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='V_Z', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RCS_DBSM', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXISTENCE_PROBABILITY', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_ID', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_XX', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_XY', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_XZ', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_YX', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_YY', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_YZ', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_ZX', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_ZY', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COV_ZZ', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RADIAL_DISTANCE', index=18, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AZIMUTH_ANGLE', index=19, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ELEVATION_ANGLE', index=20, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VELOCITY_XS', index=21, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RADIAL_DISTANCE_VARIANCE', index=22, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AZIMUTH_ANGLE_VARIANCE', index=23, number=23,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ELEVATION_ANGLE_VARIANCE', index=24, number=24,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VELOCITY_VARIANCE', index=25, number=25,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACCEL_XS', index=26, number=26,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNT_ALIVE', index=27, number=27,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REFLECTED_POWER_DB', index=28, number=28,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='R', index=29, number=29,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='G', index=30, number=30,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='B', index=31, number=31,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLASS_ID', index=32, number=32,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INSTANCE_ID', index=33, number=33,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIMESTAMP', index=34, number=34,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=504,
  serialized_end=1040,
)
_sym_db.RegisterEnumDescriptor(_RADARPOINTCLOUD_CHANNELTYPE)


_RADARPOINTCLOUD_ANNOTATIONSENTRY = _descriptor.Descriptor(
  name='AnnotationsEntry',
  full_name='dgp.proto.RadarPointCloud.AnnotationsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dgp.proto.RadarPointCloud.AnnotationsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dgp.proto.RadarPointCloud.AnnotationsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=430,
)

_RADARPOINTCLOUD_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='dgp.proto.RadarPointCloud.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dgp.proto.RadarPointCloud.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dgp.proto.RadarPointCloud.MetadataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=501,
)

_RADARPOINTCLOUD = _descriptor.Descriptor(
  name='RadarPointCloud',
  full_name='dgp.proto.RadarPointCloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='dgp.proto.RadarPointCloud.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='dgp.proto.RadarPointCloud.annotations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='dgp.proto.RadarPointCloud.metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point_format', full_name='dgp.proto.RadarPointCloud.point_format', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point_fields', full_name='dgp.proto.RadarPointCloud.point_fields', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='dgp.proto.RadarPointCloud.pose', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RADARPOINTCLOUD_ANNOTATIONSENTRY, _RADARPOINTCLOUD_METADATAENTRY, ],
  enum_types=[
    _RADARPOINTCLOUD_CHANNELTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=1040,
)

_RADARPOINTCLOUD_ANNOTATIONSENTRY.containing_type = _RADARPOINTCLOUD
_RADARPOINTCLOUD_METADATAENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_RADARPOINTCLOUD_METADATAENTRY.containing_type = _RADARPOINTCLOUD
_RADARPOINTCLOUD.fields_by_name['annotations'].message_type = _RADARPOINTCLOUD_ANNOTATIONSENTRY
_RADARPOINTCLOUD.fields_by_name['metadata'].message_type = _RADARPOINTCLOUD_METADATAENTRY
_RADARPOINTCLOUD.fields_by_name['point_format'].enum_type = _RADARPOINTCLOUD_CHANNELTYPE
_RADARPOINTCLOUD.fields_by_name['pose'].message_type = dgp_dot_proto_dot_geometry__pb2._POSE
_RADARPOINTCLOUD_CHANNELTYPE.containing_type = _RADARPOINTCLOUD
DESCRIPTOR.message_types_by_name['RadarPointCloud'] = _RADARPOINTCLOUD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadarPointCloud = _reflection.GeneratedProtocolMessageType('RadarPointCloud', (_message.Message,), {

  'AnnotationsEntry' : _reflection.GeneratedProtocolMessageType('AnnotationsEntry', (_message.Message,), {
    'DESCRIPTOR' : _RADARPOINTCLOUD_ANNOTATIONSENTRY,
    '__module__' : 'dgp.proto.radar_point_cloud_pb2'
    # @@protoc_insertion_point(class_scope:dgp.proto.RadarPointCloud.AnnotationsEntry)
    })
  ,

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _RADARPOINTCLOUD_METADATAENTRY,
    '__module__' : 'dgp.proto.radar_point_cloud_pb2'
    # @@protoc_insertion_point(class_scope:dgp.proto.RadarPointCloud.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _RADARPOINTCLOUD,
  '__module__' : 'dgp.proto.radar_point_cloud_pb2'
  # @@protoc_insertion_point(class_scope:dgp.proto.RadarPointCloud)
  })
_sym_db.RegisterMessage(RadarPointCloud)
_sym_db.RegisterMessage(RadarPointCloud.AnnotationsEntry)
_sym_db.RegisterMessage(RadarPointCloud.MetadataEntry)


_RADARPOINTCLOUD_ANNOTATIONSENTRY._options = None
_RADARPOINTCLOUD_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
