# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgp.proto import identifiers_pb2 as dgp_dot_proto_dot_identifiers__pb2
from dgp.proto import image_pb2 as dgp_dot_proto_dot_image__pb2
from dgp.proto import point_cloud_pb2 as dgp_dot_proto_dot_point__cloud__pb2
from dgp.proto import geometry_pb2 as dgp_dot_proto_dot_geometry__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dgp/proto/sample.proto',
  package='dgp.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x64gp/proto/sample.proto\x12\tdgp.proto\x1a\x1b\x64gp/proto/identifiers.proto\x1a\x15\x64gp/proto/image.proto\x1a\x1b\x64gp/proto/point_cloud.proto\x1a\x18\x64gp/proto/geometry.proto\x1a\x19google/protobuf/any.proto\"x\n\x11SampleCalibration\x12\r\n\x05names\x18\x01 \x03(\t\x12/\n\nintrinsics\x18\x02 \x03(\x0b\x32\x1b.dgp.proto.CameraIntrinsics\x12#\n\nextrinsics\x18\x03 \x03(\x0b\x32\x0f.dgp.proto.Pose\"l\n\nDatumValue\x12!\n\x05image\x18\x01 \x01(\x0b\x32\x10.dgp.proto.ImageH\x00\x12,\n\x0bpoint_cloud\x18\x02 \x01(\x0b\x32\x15.dgp.proto.PointCloudH\x00\x42\r\n\x0b\x64\x61tum_oneof\"~\n\x05\x44\x61tum\x12\x1e\n\x02id\x18\x01 \x01(\x0b\x32\x12.dgp.proto.DatumId\x12\x0b\n\x03key\x18\x02 \x01(\t\x12$\n\x05\x64\x61tum\x18\x03 \x01(\x0b\x32\x15.dgp.proto.DatumValue\x12\x10\n\x08next_key\x18\x04 \x01(\t\x12\x10\n\x08prev_key\x18\x05 \x01(\t\"\xcf\x01\n\x06Sample\x12\x1e\n\x02id\x18\x01 \x01(\x0b\x32\x12.dgp.proto.DatumId\x12\x12\n\ndatum_keys\x18\x02 \x03(\t\x12\x17\n\x0f\x63\x61libration_key\x18\x03 \x01(\t\x12\x31\n\x08metadata\x18\x04 \x03(\x0b\x32\x1f.dgp.proto.Sample.MetadataEntry\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[dgp_dot_proto_dot_identifiers__pb2.DESCRIPTOR,dgp_dot_proto_dot_image__pb2.DESCRIPTOR,dgp_dot_proto_dot_point__cloud__pb2.DESCRIPTOR,dgp_dot_proto_dot_geometry__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_SAMPLECALIBRATION = _descriptor.Descriptor(
  name='SampleCalibration',
  full_name='dgp.proto.SampleCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='dgp.proto.SampleCalibration.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intrinsics', full_name='dgp.proto.SampleCalibration.intrinsics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extrinsics', full_name='dgp.proto.SampleCalibration.extrinsics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=291,
)


_DATUMVALUE = _descriptor.Descriptor(
  name='DatumValue',
  full_name='dgp.proto.DatumValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='dgp.proto.DatumValue.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point_cloud', full_name='dgp.proto.DatumValue.point_cloud', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='datum_oneof', full_name='dgp.proto.DatumValue.datum_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=293,
  serialized_end=401,
)


_DATUM = _descriptor.Descriptor(
  name='Datum',
  full_name='dgp.proto.Datum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dgp.proto.Datum.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='dgp.proto.Datum.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datum', full_name='dgp.proto.Datum.datum', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_key', full_name='dgp.proto.Datum.next_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prev_key', full_name='dgp.proto.Datum.prev_key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=529,
)


_SAMPLE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='dgp.proto.Sample.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dgp.proto.Sample.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='dgp.proto.Sample.MetadataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=739,
)

_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='dgp.proto.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dgp.proto.Sample.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datum_keys', full_name='dgp.proto.Sample.datum_keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calibration_key', full_name='dgp.proto.Sample.calibration_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='dgp.proto.Sample.metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SAMPLE_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=739,
)

_SAMPLECALIBRATION.fields_by_name['intrinsics'].message_type = dgp_dot_proto_dot_geometry__pb2._CAMERAINTRINSICS
_SAMPLECALIBRATION.fields_by_name['extrinsics'].message_type = dgp_dot_proto_dot_geometry__pb2._POSE
_DATUMVALUE.fields_by_name['image'].message_type = dgp_dot_proto_dot_image__pb2._IMAGE
_DATUMVALUE.fields_by_name['point_cloud'].message_type = dgp_dot_proto_dot_point__cloud__pb2._POINTCLOUD
_DATUMVALUE.oneofs_by_name['datum_oneof'].fields.append(
  _DATUMVALUE.fields_by_name['image'])
_DATUMVALUE.fields_by_name['image'].containing_oneof = _DATUMVALUE.oneofs_by_name['datum_oneof']
_DATUMVALUE.oneofs_by_name['datum_oneof'].fields.append(
  _DATUMVALUE.fields_by_name['point_cloud'])
_DATUMVALUE.fields_by_name['point_cloud'].containing_oneof = _DATUMVALUE.oneofs_by_name['datum_oneof']
_DATUM.fields_by_name['id'].message_type = dgp_dot_proto_dot_identifiers__pb2._DATUMID
_DATUM.fields_by_name['datum'].message_type = _DATUMVALUE
_SAMPLE_METADATAENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_SAMPLE_METADATAENTRY.containing_type = _SAMPLE
_SAMPLE.fields_by_name['id'].message_type = dgp_dot_proto_dot_identifiers__pb2._DATUMID
_SAMPLE.fields_by_name['metadata'].message_type = _SAMPLE_METADATAENTRY
DESCRIPTOR.message_types_by_name['SampleCalibration'] = _SAMPLECALIBRATION
DESCRIPTOR.message_types_by_name['DatumValue'] = _DATUMVALUE
DESCRIPTOR.message_types_by_name['Datum'] = _DATUM
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleCalibration = _reflection.GeneratedProtocolMessageType('SampleCalibration', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLECALIBRATION,
  __module__ = 'dgp.proto.sample_pb2'
  # @@protoc_insertion_point(class_scope:dgp.proto.SampleCalibration)
  ))
_sym_db.RegisterMessage(SampleCalibration)

DatumValue = _reflection.GeneratedProtocolMessageType('DatumValue', (_message.Message,), dict(
  DESCRIPTOR = _DATUMVALUE,
  __module__ = 'dgp.proto.sample_pb2'
  # @@protoc_insertion_point(class_scope:dgp.proto.DatumValue)
  ))
_sym_db.RegisterMessage(DatumValue)

Datum = _reflection.GeneratedProtocolMessageType('Datum', (_message.Message,), dict(
  DESCRIPTOR = _DATUM,
  __module__ = 'dgp.proto.sample_pb2'
  # @@protoc_insertion_point(class_scope:dgp.proto.Datum)
  ))
_sym_db.RegisterMessage(Datum)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _SAMPLE_METADATAENTRY,
    __module__ = 'dgp.proto.sample_pb2'
    # @@protoc_insertion_point(class_scope:dgp.proto.Sample.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _SAMPLE,
  __module__ = 'dgp.proto.sample_pb2'
  # @@protoc_insertion_point(class_scope:dgp.proto.Sample)
  ))
_sym_db.RegisterMessage(Sample)
_sym_db.RegisterMessage(Sample.MetadataEntry)


_SAMPLE_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
