# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/statistics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dgp/proto/statistics.proto',
  package='dgp.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x64gp/proto/statistics.proto\x12\tdgp.proto\"\xb2\x02\n\x11\x44\x61tasetStatistics\x12\x46\n\x10image_statistics\x18\x01 \x01(\x0b\x32,.dgp.proto.DatasetStatistics.ImageStatistics\x12P\n\x15pointcloud_statistics\x18\x02 \x01(\x0b\x32\x31.dgp.proto.DatasetStatistics.PointCloudStatistics\x1a>\n\x0fImageStatistics\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x0c\n\x04mean\x18\x02 \x03(\x02\x12\x0e\n\x06stddev\x18\x03 \x03(\x02\x1a\x43\n\x14PointCloudStatistics\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x0c\n\x04mean\x18\x02 \x03(\x02\x12\x0e\n\x06stddev\x18\x03 \x03(\x02\x62\x06proto3'
)




_DATASETSTATISTICS_IMAGESTATISTICS = _descriptor.Descriptor(
  name='ImageStatistics',
  full_name='dgp.proto.DatasetStatistics.ImageStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='dgp.proto.DatasetStatistics.ImageStatistics.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='dgp.proto.DatasetStatistics.ImageStatistics.mean', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stddev', full_name='dgp.proto.DatasetStatistics.ImageStatistics.stddev', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=279,
)

_DATASETSTATISTICS_POINTCLOUDSTATISTICS = _descriptor.Descriptor(
  name='PointCloudStatistics',
  full_name='dgp.proto.DatasetStatistics.PointCloudStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='dgp.proto.DatasetStatistics.PointCloudStatistics.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='dgp.proto.DatasetStatistics.PointCloudStatistics.mean', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stddev', full_name='dgp.proto.DatasetStatistics.PointCloudStatistics.stddev', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=348,
)

_DATASETSTATISTICS = _descriptor.Descriptor(
  name='DatasetStatistics',
  full_name='dgp.proto.DatasetStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_statistics', full_name='dgp.proto.DatasetStatistics.image_statistics', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointcloud_statistics', full_name='dgp.proto.DatasetStatistics.pointcloud_statistics', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DATASETSTATISTICS_IMAGESTATISTICS, _DATASETSTATISTICS_POINTCLOUDSTATISTICS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=348,
)

_DATASETSTATISTICS_IMAGESTATISTICS.containing_type = _DATASETSTATISTICS
_DATASETSTATISTICS_POINTCLOUDSTATISTICS.containing_type = _DATASETSTATISTICS
_DATASETSTATISTICS.fields_by_name['image_statistics'].message_type = _DATASETSTATISTICS_IMAGESTATISTICS
_DATASETSTATISTICS.fields_by_name['pointcloud_statistics'].message_type = _DATASETSTATISTICS_POINTCLOUDSTATISTICS
DESCRIPTOR.message_types_by_name['DatasetStatistics'] = _DATASETSTATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatasetStatistics = _reflection.GeneratedProtocolMessageType('DatasetStatistics', (_message.Message,), {

  'ImageStatistics' : _reflection.GeneratedProtocolMessageType('ImageStatistics', (_message.Message,), {
    'DESCRIPTOR' : _DATASETSTATISTICS_IMAGESTATISTICS,
    '__module__' : 'dgp.proto.statistics_pb2'
    # @@protoc_insertion_point(class_scope:dgp.proto.DatasetStatistics.ImageStatistics)
    })
  ,

  'PointCloudStatistics' : _reflection.GeneratedProtocolMessageType('PointCloudStatistics', (_message.Message,), {
    'DESCRIPTOR' : _DATASETSTATISTICS_POINTCLOUDSTATISTICS,
    '__module__' : 'dgp.proto.statistics_pb2'
    # @@protoc_insertion_point(class_scope:dgp.proto.DatasetStatistics.PointCloudStatistics)
    })
  ,
  'DESCRIPTOR' : _DATASETSTATISTICS,
  '__module__' : 'dgp.proto.statistics_pb2'
  # @@protoc_insertion_point(class_scope:dgp.proto.DatasetStatistics)
  })
_sym_db.RegisterMessage(DatasetStatistics)
_sym_db.RegisterMessage(DatasetStatistics.ImageStatistics)
_sym_db.RegisterMessage(DatasetStatistics.PointCloudStatistics)


# @@protoc_insertion_point(module_scope)
