name: coverage
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      OS: ubuntu-18.04
      PYTHON: '3.6'
      COVERAGE_TOTAL: 24 #Coverage threshold percentage
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: ‘2’ #Original commit + code cov badge commit
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.21 numpy==1.19.4
        pip install -r requirements.txt
        pip install coverage-badge
        coverage run -m pytest
        coverage-badge -f -o docs/coverage.svg
    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v6
      id: changed_files
      with:
        files: docs/coverage.svg
    - name: Commit code coverage badge
      if: ${{ steps.changed_files.outputs.files_changed == 'true' && github.event_name != 'pull_request'}}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/coverage.svg
        git commit -m "test: update coverage.svg"
    - name: Push code coverage badge
      if: ${{ steps.changed_files.outputs.files_changed == 'true' && github.event_name != 'pull_request'}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.github_token }}
        branch: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Coverage testing
      if: github.event_name == 'pull_request'
      id: pytester-cov
      uses: alexanderdamiani/pytester-cov@v1.2.0
      with:
        pytest-root-dir: './dgp'
        cov-omit-list: 'tests/*, docs/*, dgp/contribs/pd/*, dgp/proto/*'
        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
    - name: Coverage total fail - exit
      if: ${{github.event_name == 'pull_request' && steps.pytester-cov.outputs.cov-threshold-total-fail == 'false' }}
      run: |
        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
        exit 1