name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate Report
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.21 numpy==1.19.4
        pip install -r requirements.txt
        pip install coverage
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        flags: unittests # optional
