name: pre-merge
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-merge-tests:
    runs-on: ubuntu-20.04
    env:
      ENVIRONMENT: TEST_RUNNER
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint commit message with commitlint
        # Documentation: https://github.com/wagoid/commitlint-github-action
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml
      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.21 numpy==1.23.2
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint all files with pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
