name: pre-merge
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-merge-tests:
    runs-on: ubuntu-18.04
    env:
      ENVIRONMENT: TEST_RUNNER
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint commit message with commitlint
        # Documentation: https://github.com/wagoid/commitlint-github-action
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.21 numpy==1.19.4
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint all files with pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
      - name: Lint code base with SuperLinter
        # Documentation: https://github.com/github/super-linter#how-to-use
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_EXCLUDE: .*pb2*py
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: false # Only new or edited files will be parsed for validation.
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_GITLEAKS: false # Handled by pre-commit.
          VALIDATE_HTML: false # Handled by pre-commit.
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false # Handled by pre-commit.
          VALIDATE_PROTOBUF: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false # Formatted by YAPF.
          VALIDATE_PYTHON_ISORT: false # Formatted by YAPF.
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false # Handled by pre-commit.
          VALIDATE_SHELL_SHFMT: false # Handled by pre-commit.
